mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import include, url

from . import views


app_name = 'polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^new_question/$', views.new_question, name='new_question')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    published_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.published_at >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

class Thing(models.Model):
    content = models.CharField(max_length=200)

    def __str__(self):
        return self.content

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, Thing



def index(request):
    if request.method == 'POST':
        print('post request')
    else:
        latest_questions = Question.objects.filter(published_at__lte=timezone.now()) \
                                            .order_by('-published_at')
        return render(request, 'polls/index.html', {'latest_questions': latest_questions})
    

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay question voting form
        error_message = "You didn't select a choice."
        context = {
            'question': question,
            'error_message': error_message
        }
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def new_question(request):
    question_text = request.POST['question_text']
    if not question_text:
        return redirect(reverse('polls:index'))

    question = Question(question_text=request.POST['question_text'])
    question.save()
    thing = Thing(content=question.question_text)
    thing.save()
    return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.text }}</label>
        <br/>
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

<a href="{% url 'polls:index' %}">Back to Polls</a>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No recent polls.</p>
{% endif %}

<form action="{% url 'polls:new_question' %}" method='POST'>
    {% csrf_token %}
    <input type="text" name="question_text" id="question_text" />
    <label for="question_text">Question Wording</label>
    <br/>
    <input type="submit" value="Save" />
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.votes }} votes -- {{ choice.text }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>